export const DEMO_REFERENCE_DATE = "2026-06-25T18:00:00+08:00";
const DEMO_REFERENCE_YEAR = 2026;
const DEMO_REFERENCE_MONTH_INDEX = 5;

export const DEMO_ACCOUNTS = [
  { id: "demo_account_wechat", name: "微信", openingBalance: 3600 },
  { id: "demo_account_bank", name: "银行卡", openingBalance: 26200 },
  { id: "demo_account_alipay", name: "支付宝", openingBalance: 2200 },
  { id: "demo_account_other", name: "其他", openingBalance: 600 },
];

export const DEMO_BUDGETS = {
  "餐饮": 2200,
  "交通": 500,
  "购物": 1200,
  "运动": 3000,
  "生活": 7200,
  "健康": 900,
  "AI 工具": 900,
  "订阅": 400,
  "学习": 900,
  "娱乐": 500,
  "旅行": 1800,
  "其他": 500,
};

export const DEMO_TRANSACTIONS = [
  {
    id: "demo_txn_20260601_salary",
    type: "income",
    occurredAt: "2026-06-01T09:10:00+08:00",
    amount: 30000,
    currency: "CNY",
    book: "日常账本",
    account: "银行卡",
    category: "薪酬",
    title: "月初工资",
    merchant: "公司",
    tags: "salary",
  },
  {
    id: "demo_txn_20260601_rent",
    type: "expense",
    occurredAt: "2026-06-01T20:20:00+08:00",
    amount: 6800,
    currency: "CNY",
    book: "日常账本",
    account: "银行卡",
    category: "生活",
    title: "房租",
    merchant: "房东",
    tags: "home",
  },
  {
    id: "demo_txn_20260602_breakfast",
    type: "expense",
    occurredAt: "2026-06-02T08:15:00+08:00",
    amount: 28,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "早餐",
    merchant: "楼下早餐店",
    tags: "breakfast",
  },
  {
    id: "demo_txn_20260602_metro",
    type: "expense",
    occurredAt: "2026-06-02T09:05:00+08:00",
    amount: 8,
    currency: "CNY",
    book: "日常账本",
    account: "支付宝",
    category: "交通",
    title: "地铁",
    merchant: "上海地铁",
    tags: "commute",
  },
  {
    id: "demo_txn_20260602_ai",
    type: "expense",
    occurredAt: "2026-06-02T22:30:00+08:00",
    amount: 160,
    currency: "CNY",
    book: "日常账本",
    account: "银行卡",
    category: "AI 工具",
    title: "ChatGPT",
    merchant: "OpenAI",
    tags: "ai subscription",
  },
  {
    id: "demo_txn_20260603_lunch",
    type: "expense",
    occurredAt: "2026-06-03T12:35:00+08:00",
    amount: 45,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "工作日午餐",
    merchant: "简餐",
    tags: "lunch",
  },
  {
    id: "demo_txn_20260603_coffee",
    type: "expense",
    occurredAt: "2026-06-03T15:40:00+08:00",
    amount: 24,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "咖啡",
    merchant: "Manner",
    tags: "coffee",
  },
  {
    id: "demo_txn_20260604_shoes",
    type: "expense",
    occurredAt: "2026-06-04T21:10:00+08:00",
    amount: 899,
    currency: "CNY",
    book: "训练账本",
    account: "银行卡",
    category: "运动",
    title: "越野跑鞋",
    merchant: "运动旗舰店",
    tags: "gear trail",
  },
  {
    id: "demo_txn_20260605_freelance",
    type: "income",
    occurredAt: "2026-06-05T10:00:00+08:00",
    amount: 4200,
    currency: "CNY",
    book: "日常账本",
    account: "支付宝",
    category: "薪酬",
    title: "项目尾款",
    merchant: "客户 A",
    tags: "project",
  },
  {
    id: "demo_txn_20260605_taxi",
    type: "expense",
    occurredAt: "2026-06-05T19:18:00+08:00",
    amount: 36,
    currency: "CNY",
    book: "日常账本",
    account: "支付宝",
    category: "交通",
    title: "打车",
    merchant: "滴滴",
    tags: "taxi",
  },
  {
    id: "demo_txn_20260606_grocery",
    type: "expense",
    occurredAt: "2026-06-06T18:22:00+08:00",
    amount: 268,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "购物",
    title: "超市采购",
    merchant: "盒马",
    tags: "grocery",
  },
  {
    id: "demo_txn_20260607_supply",
    type: "expense",
    occurredAt: "2026-06-07T07:25:00+08:00",
    amount: 72,
    currency: "CNY",
    book: "训练账本",
    account: "支付宝",
    category: "运动",
    title: "长跑补给",
    merchant: "便利店",
    tags: "run fuel",
  },
  {
    id: "demo_txn_20260608_dinner",
    type: "expense",
    occurredAt: "2026-06-08T19:45:00+08:00",
    amount: 126,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "晚餐",
    merchant: "湘菜馆",
    tags: "dinner",
  },
  {
    id: "demo_txn_20260609_book",
    type: "expense",
    occurredAt: "2026-06-09T21:05:00+08:00",
    amount: 98,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "学习",
    title: "技术书",
    merchant: "微信读书",
    tags: "study",
  },
  {
    id: "demo_txn_20260610_health",
    type: "expense",
    occurredAt: "2026-06-10T17:50:00+08:00",
    amount: 260,
    currency: "CNY",
    book: "训练账本",
    account: "银行卡",
    category: "健康",
    title: "运动康复",
    merchant: "康复中心",
    tags: "recovery",
  },
  {
    id: "demo_txn_20260611_lunch",
    type: "expense",
    occurredAt: "2026-06-11T12:20:00+08:00",
    amount: 38,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "午餐",
    merchant: "面馆",
    tags: "lunch",
  },
  {
    id: "demo_txn_20260612_subscription",
    type: "expense",
    occurredAt: "2026-06-12T10:10:00+08:00",
    amount: 68,
    currency: "CNY",
    book: "日常账本",
    account: "银行卡",
    category: "订阅",
    title: "云盘订阅",
    merchant: "iCloud",
    tags: "subscription",
  },
  {
    id: "demo_txn_20260613_train",
    type: "expense",
    occurredAt: "2026-06-13T08:30:00+08:00",
    amount: 312,
    currency: "CNY",
    book: "旅行账本",
    account: "支付宝",
    category: "旅行",
    title: "高铁票",
    merchant: "12306",
    project: "杭州周末旅行",
    tags: "travel train",
  },
  {
    id: "demo_txn_20260614_hotel",
    type: "expense",
    occurredAt: "2026-06-14T16:15:00+08:00",
    amount: 680,
    currency: "CNY",
    book: "旅行账本",
    account: "银行卡",
    category: "旅行",
    title: "酒店定金",
    merchant: "Booking",
    project: "杭州周末旅行",
    tags: "travel hotel",
  },
  {
    id: "demo_txn_20260615_interest",
    type: "income",
    occurredAt: "2026-06-15T09:00:00+08:00",
    amount: 800,
    currency: "CNY",
    book: "日常账本",
    account: "银行卡",
    category: "薪酬",
    title: "稿费",
    merchant: "平台",
    tags: "income",
  },
  {
    id: "demo_txn_20260615_race",
    type: "expense",
    occurredAt: "2026-06-15T20:20:00+08:00",
    amount: 388,
    currency: "CNY",
    book: "训练账本",
    account: "微信",
    category: "运动",
    title: "越野赛报名",
    merchant: "赛事平台",
    project: "崇礼越野赛",
    tags: "race",
  },
  {
    id: "demo_txn_20260616_commute",
    type: "expense",
    occurredAt: "2026-06-16T08:40:00+08:00",
    amount: 8,
    currency: "CNY",
    book: "日常账本",
    account: "支付宝",
    category: "交通",
    title: "通勤",
    merchant: "地铁",
    tags: "commute",
  },
  {
    id: "demo_txn_20260616_friend_dinner",
    type: "expense",
    occurredAt: "2026-06-16T20:05:00+08:00",
    amount: 156,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "朋友聚餐",
    merchant: "日料",
    tags: "dinner",
  },
  {
    id: "demo_txn_20260617_massage",
    type: "expense",
    occurredAt: "2026-06-17T18:30:00+08:00",
    amount: 298,
    currency: "CNY",
    book: "训练账本",
    account: "银行卡",
    category: "健康",
    title: "放松按摩",
    merchant: "运动恢复店",
    project: "崇礼越野赛",
    tags: "recovery",
  },
  {
    id: "demo_txn_20260618_vest",
    type: "expense",
    occurredAt: "2026-06-18T21:40:00+08:00",
    amount: 459,
    currency: "CNY",
    book: "训练账本",
    account: "银行卡",
    category: "运动",
    title: "跑步背心",
    merchant: "装备店",
    project: "崇礼越野赛",
    tags: "gear",
  },
  {
    id: "demo_txn_20260619_course",
    type: "expense",
    occurredAt: "2026-06-19T22:00:00+08:00",
    amount: 199,
    currency: "CNY",
    book: "日常账本",
    account: "银行卡",
    category: "学习",
    title: "线上课程",
    merchant: "课程平台",
    tags: "course",
  },
  {
    id: "demo_txn_20260620_movie",
    type: "expense",
    occurredAt: "2026-06-20T20:20:00+08:00",
    amount: 88,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "娱乐",
    title: "电影",
    merchant: "影院",
    tags: "movie",
  },
  {
    id: "demo_txn_20260621_coffee",
    type: "expense",
    occurredAt: "2026-06-21T14:00:00+08:00",
    amount: 32,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "周末咖啡",
    merchant: "咖啡店",
    tags: "coffee",
  },
  {
    id: "demo_txn_20260622_trail_meal",
    type: "expense",
    occurredAt: "2026-06-22T13:10:00+08:00",
    amount: 64,
    currency: "CNY",
    book: "训练账本",
    account: "支付宝",
    category: "运动",
    title: "训练后简餐",
    merchant: "便利店",
    tags: "run meal",
  },
  {
    id: "demo_txn_20260623_ai_credit",
    type: "expense",
    occurredAt: "2026-06-23T10:30:00+08:00",
    amount: 300,
    currency: "CNY",
    book: "日常账本",
    account: "银行卡",
    category: "AI 工具",
    title: "ChatGPT",
    merchant: "OpenAI",
    tags: "ai api",
  },
  {
    id: "demo_txn_20260623_supermarket",
    type: "expense",
    occurredAt: "2026-06-23T19:15:00+08:00",
    amount: 214,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "购物",
    title: "生活用品",
    merchant: "超市",
    tags: "grocery",
  },
  {
    id: "demo_txn_20260624_lunch",
    type: "expense",
    occurredAt: "2026-06-24T12:45:00+08:00",
    amount: 52,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "午餐",
    merchant: "轻食",
    tags: "lunch",
  },
  {
    id: "demo_txn_20260624_metro",
    type: "expense",
    occurredAt: "2026-06-24T18:05:00+08:00",
    amount: 12,
    currency: "CNY",
    book: "日常账本",
    account: "支付宝",
    category: "交通",
    title: "晚高峰通勤",
    merchant: "地铁",
    tags: "commute",
  },
  {
    id: "demo_txn_20260624_cable",
    type: "expense",
    occurredAt: "2026-06-24T21:18:00+08:00",
    amount: 79,
    currency: "CNY",
    book: "日常账本",
    account: "支付宝",
    category: "购物",
    title: "数据线",
    merchant: "数码店",
    tags: "gear tech",
  },
  {
    id: "demo_txn_20260625_project_income",
    type: "income",
    occurredAt: "2026-06-25T10:00:00+08:00",
    amount: 1200,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "薪酬",
    title: "咨询款",
    merchant: "客户 B",
    tags: "income project",
  },
  {
    id: "demo_txn_20260625_breakfast",
    type: "expense",
    occurredAt: "2026-06-25T08:10:00+08:00",
    amount: 18,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "早餐",
    merchant: "便利店",
    tags: "breakfast",
  },
  {
    id: "demo_txn_20260625_coffee",
    type: "expense",
    occurredAt: "2026-06-25T11:25:00+08:00",
    amount: 28,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "咖啡",
    merchant: "Manner",
    tags: "coffee",
  },
  {
    id: "demo_txn_20260625_metro",
    type: "expense",
    occurredAt: "2026-06-25T18:30:00+08:00",
    amount: 8,
    currency: "CNY",
    book: "日常账本",
    account: "支付宝",
    category: "交通",
    title: "地铁",
    merchant: "上海地铁",
    tags: "commute",
  },
  {
    id: "demo_txn_20260625_dinner",
    type: "expense",
    occurredAt: "2026-06-25T20:10:00+08:00",
    amount: 92,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "晚餐",
    merchant: "小馆子",
    tags: "dinner",
  },
  {
    id: "demo_txn_20260625_stationery",
    type: "expense",
    occurredAt: "2026-06-25T21:05:00+08:00",
    amount: 36,
    currency: "CNY",
    book: "日常账本",
    account: "其他",
    category: "学习",
    title: "笔记本",
    merchant: "文具店",
    tags: "study",
  },
  {
    id: "demo_txn_20260530_previous_month",
    type: "expense",
    occurredAt: "2026-05-30T19:30:00+08:00",
    amount: 188,
    currency: "CNY",
    book: "日常账本",
    account: "微信",
    category: "餐饮",
    title: "上月聚餐",
    merchant: "餐厅",
    tags: "previous-month",
  },
];

function daysInMonth(year, monthIndex) {
  return new Date(year, monthIndex + 1, 0).getDate();
}

function shiftDemoOccurredAt(value, anchor = new Date()) {
  const target = anchor instanceof Date ? anchor : new Date(anchor);
  if (Number.isNaN(target.getTime())) return value;
  const match = String(value || "").match(/^(\d{4})-(\d{2})-(\d{2})(T.*)$/);
  if (!match) return value;

  const sourceYear = Number(match[1]);
  const sourceMonthIndex = Number(match[2]) - 1;
  const sourceDay = Number(match[3]);
  const monthOffset =
    (sourceYear * 12 + sourceMonthIndex) -
    (DEMO_REFERENCE_YEAR * 12 + DEMO_REFERENCE_MONTH_INDEX);
  const targetMonthIndex = target.getFullYear() * 12 + target.getMonth() + monthOffset;
  const shiftedYear = Math.floor(targetMonthIndex / 12);
  const shiftedMonthIndex = targetMonthIndex % 12;
  const shiftedDay = Math.min(sourceDay, daysInMonth(shiftedYear, shiftedMonthIndex));
  const pad = (part) => String(part).padStart(2, "0");

  return `${shiftedYear}-${pad(shiftedMonthIndex + 1)}-${pad(shiftedDay)}${match[4]}`;
}

export function demoTransactionsForMonth(anchor = new Date()) {
  return DEMO_TRANSACTIONS.map((txn) => ({
    ...txn,
    occurredAt: shiftDemoOccurredAt(txn.occurredAt, anchor),
  }));
}
